# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main", "stage" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Install Gradle
          run: |
            wget https://services.gradle.org/distributions/gradle-7.3-bin.zip
            unzip -d /opt gradle-7.3-bin.zip
            export PATH=$PATH:/opt/gradle-7.3/bin
            gradle -v
      - name: Build and Run Tests
        run: gradle test
      - name: Publish Test Report
        if: ${{ always() }} #publish report even if the tests are failing
        uses: scacap/action-surefire-report@v1