name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.3-bin.zip
          unzip -d /opt gradle-7.3-bin.zip
          export PATH=$PATH:/opt/gradle-7.3/bin
          gradle -v

      - name: Build and Run Tests
        run: gradle test

      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
